/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as CompareRouteImport } from "./routes/compare"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PropertiesIndexRouteImport } from "./routes/properties/index"
import { Route as PropertiesNewRouteImport } from "./routes/properties/new"
import { Route as PropertiesIdRouteImport } from "./routes/properties/$id"

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: "/compare",
  path: "/compare",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: "/properties/",
  path: "/properties/",
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesNewRoute = PropertiesNewRouteImport.update({
  id: "/properties/new",
  path: "/properties/new",
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: "/properties/$id",
  path: "/properties/$id",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/compare": typeof CompareRoute
  "/settings": typeof SettingsRoute
  "/properties/$id": typeof PropertiesIdRoute
  "/properties/new": typeof PropertiesNewRoute
  "/properties": typeof PropertiesIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/compare": typeof CompareRoute
  "/settings": typeof SettingsRoute
  "/properties/$id": typeof PropertiesIdRoute
  "/properties/new": typeof PropertiesNewRoute
  "/properties": typeof PropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/compare": typeof CompareRoute
  "/settings": typeof SettingsRoute
  "/properties/$id": typeof PropertiesIdRoute
  "/properties/new": typeof PropertiesNewRoute
  "/properties/": typeof PropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/compare"
    | "/settings"
    | "/properties/$id"
    | "/properties/new"
    | "/properties"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/compare"
    | "/settings"
    | "/properties/$id"
    | "/properties/new"
    | "/properties"
  id:
    | "__root__"
    | "/"
    | "/compare"
    | "/settings"
    | "/properties/$id"
    | "/properties/new"
    | "/properties/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  SettingsRoute: typeof SettingsRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertiesNewRoute: typeof PropertiesNewRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/compare": {
      id: "/compare"
      path: "/compare"
      fullPath: "/compare"
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/properties/": {
      id: "/properties/"
      path: "/properties"
      fullPath: "/properties"
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/properties/new": {
      id: "/properties/new"
      path: "/properties/new"
      fullPath: "/properties/new"
      preLoaderRoute: typeof PropertiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/properties/$id": {
      id: "/properties/$id"
      path: "/properties/$id"
      fullPath: "/properties/$id"
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  SettingsRoute: SettingsRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  PropertiesNewRoute: PropertiesNewRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
